import {
  Wallet,
  Landmark,
  PiggyBank,
  CreditCard,
  Banknote,
  TrendingUp,
  Building2,
  Home,
  ShoppingCart,
  Car,
  Plug,
  Utensils,
  Clapperboard,
  HeartPulse,
  Shield,
  ShoppingBag,
  GraduationCap,
  Plane,
  Repeat,
  MoreHorizontal,
  Briefcase,
  Laptop,
  Gift,
  Tag,
  Target,
  Heart,
  Trophy,
  Umbrella,
  Baby,
  Dog,
  Dumbbell,
  Music,
  Book,
  Coffee,
  Smartphone,
  type LucideIcon,
} from "lucide-react"

export const ICON_MAP: Record<string, LucideIcon> = {
  wallet: Wallet,
  landmark: Landmark,
  "piggy-bank": PiggyBank,
  "credit-card": CreditCard,
  banknote: Banknote,
  "trending-up": TrendingUp,
  building: Building2,
  home: Home,
  "shopping-cart": ShoppingCart,
  car: Car,
  plug: Plug,
  utensils: Utensils,
  clapperboard: Clapperboard,
  "heart-pulse": HeartPulse,
  shield: Shield,
  "shopping-bag": ShoppingBag,
  "graduation-cap": GraduationCap,
  plane: Plane,
  repeat: Repeat,
  "more-horizontal": MoreHorizontal,
  briefcase: Briefcase,
  laptop: Laptop,
  gift: Gift,
  tag: Tag,
  target: Target,
  heart: Heart,
  trophy: Trophy,
  umbrella: Umbrella,
  baby: Baby,
  dog: Dog,
  dumbbell: Dumbbell,
  music: Music,
  book: Book,
  coffee: Coffee,
  smartphone: Smartphone,
}

export const ICON_NAMES = Object.keys(ICON_MAP)

export function getIcon(name: string): LucideIcon {
  return ICON_MAP[name] ?? Tag
}

export const COLOR_PALETTE = [
  "#6366f1",
  "#8b5cf6",
  "#ec4899",
  "#ef4444",
  "#f97316",
  "#f59e0b",
  "#eab308",
  "#84cc16",
  "#22c55e",
  "#14b8a6",
  "#06b6d4",
  "#0ea5e9",
  "#3b82f6",
  "#71717a",
]
